apiVersion: v1
kind: Secret
metadata:
  name: {{ include "myapp.fullname" . }}
type: Opaque
data:
# NOTE: You can get your own API key by going to https://rapidapi.com/weatherapi/api/weatherapi-com/ and subscribing to the service (free)
  APIKEY: {{ "ab43c038e6msh1d167f7d8658122p1ad9cfjsn658814799aea" | b64enc }}
